### ISSUE TITLE
Feature request: allow multiple TURBO_TOKEN as comman separated value

### ISSUE THREAD

**Issue by parkjh** [fox1t/turborepo-remote-cache#11]
Hi,
I wanted to ask whether there were any objections to allow multiple values for `TURBO_TOKEN` to be parsed as comma separated?
https://github.com/fox1t/turborepo-remote-cache/blob/93eddd010bd8f2c243f291c99d11c02caeb3db48/src/app.ts#L19
if not I can raise a pull request that changes the above line to `allowedTokens: app.config.TURBO_TOKEN.split(','),`

**Comment by fox1t** [comment]
I think it can be useful! PR is welcome!
