### ISSUE TITLE
publish on npm?

### ISSUE THREAD

**Issue by NullVoxPopuli** [fox1t/turborepo-remote-cache#20]
for folks wanting to run this locally between worktrees, not needing docker or needing to clone + compile would be a big help.

just a lil `npx turborepo-remote-cache` or something would be great :D <3

**Comment by NullVoxPopuli** [comment]
almost!

kinda -- the main thing is that, in order to use `turborepo-remote-cache` today, I have to ([instructions described here](https://github.com/NullVoxPopuli/limber/pull/475/files#diff-ae7ccceccbdfb21b040f921cb333bf1d7a3b72ea15578d02c53f8538caa98b7cR17) in [this demo PR](https://github.com/NullVoxPopuli/limber/pull/475)):
 - clone the repo
 - cd into the repo
 - npm install
 - npm run prebuild
 - npm run build
 
 which isn't scalable across more than a few people. 
 
 so, if we could add `turborepo-remote-cache` to our monorepo's root package.json, we could then "just use the pre-built tool".
 With published packages, we also get security scanning (from whitesource or whatever else folks use).

**Comment by NullVoxPopuli** [comment]
> Why do you want to run more than one instance of remote-cache?

Because my team has access to S3 management, but we can't spin up new servers (this is a hard requirement we can't get around right now).
Additionally, even in a solo-server environment, I would not want to build from source. 
Releasing is a good way to communicate bugfixes, features, breaking changes, etc (SemVer, etc)

> The whole point of this project is to have a shared caching server between several developers.

For my team, the plan is to (atm):
 - (hopefully) install `turborepo-remote-cache` (provided you release it on npm <3)
 - use our existing wrapper scripts to manage the start/stop/restart of the cache server per-developer (the developers would not notice this at all, because we already use wrapper scripts for everything)
 - the cache server per-developer will access the same s3 storage, still using a shared cache between our 160+ developers (I've lost track at this point)
 - every developer already has access to S3, so they'd use their existing keys (in their local env) for the cache server to use to communicate with S3
 - allow updates of `turborepo-remote-cache` to automatically be PR'd to us via renovate / dependabot 
 - allow every version of `turborepo-remote-cache` (and its dependencies) to have security scanning (which most security scanner tools support npm packages)
 
 > I am still trying to figure out what limber does, so sorry if this is a dumb question
 
 no dumb questions!!!
 but limber isn't important -- it's just a simple monorepo and the linked PR is to demonstrate capabilities for consideration in a _very very very very very_ large internal monorepo

**Comment by fox1t** [comment]
I like the idea, and it is worth trying. @tehKapa, what do you think? This could be one of the easiest ways to deploy "serverless".

**Comment by tehKapa** [comment]
it could be a very good idea. it would become a "remoteless"

**Comment by fox1t** [comment]
@NullVoxPopuli you can now run the command you proposed :) 
Let us know if you find any issues.

**Comment by NullVoxPopuli** [comment]
thank you!!

I've updated my demo here: https://github.com/NullVoxPopuli/limber/pull/475
