### ISSUE TITLE
Vercel deployment broken

### ISSUE THREAD

**Issue by dobesv** [fox1t/turborepo-remote-cache#31]
Recently I changed this package to use the "standard" environment variables for AWS access.  However, in https://github.com/fox1t/turborepo-remote-cache/pull/30#issuecomment-1164478682 it was revealed that for Vercel deployment for whatever reason they do not allow those environment variables to be used.

Some fallback environment variables will likely be needed to support Vercel deployment.

Docs: 

- https://vercel.com/docs/concepts/projects/environment-variables#reserved-environment-variables
- https://vercel.com/support/articles/how-can-i-use-aws-sdk-environment-variables-on-vercel

Vercel deployments will not work until that is resolved.

This may be as simple as changing `vercel.ts` like this:

```
import type { VercelRequest, VercelResponse } from '@vercel/node'
import { createApp } from './app'

// Propage any environment vars APP_AWS_* to AWS_* to workaround
// vercel restriction on environment variables
Object.keys(process.env).filter(k => k.startsWith('APP_AWS_')).forEach(k => {
  process.env[k.substring(4)] = process.env[k];
})

const app = createApp()

export default async function (req: VercelRequest, res: VercelResponse) {
  await app.ready()
  app.server.emit('request', req, res)
}
```

**Comment by fox1t** [comment]
I am not sure that this is the correct snippet. We should remap `S3_` to `AWS_`.
